# Generated by Django 4.0.6 on 2022-08-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('canceled', 'canceled'), ('delivered', 'delivered')], default='opened', max_length=255),
        ),
    ]
